### ISSUE TITLE
Cannot mount "/data"

### ISSUE THREAD

**Issue by linus-ha** [TeamWin/android_device_samsung_dreamlte#2]
TWRP can not mount the data partition for factory reset, backup, etc...
I've only tried to mount the data partition in multiple stages of instlling the stock os / rom.
In cannot access the data partition in any stage.

**Comment by MS-MK** [comment]
TWRP loop again , again and again when i install it !
when i restart the systeme to get acces to my android system , 
the boot redirect me to TWRP
i no longer have acces to my android system plz help !!

**Comment by SuperSandro2000** [comment]
Did you format your device?

btw GitHub: Why are you sending me notifications for 2 year old stuff?

**Comment by linus-ha** [comment]
Sorry... Now, with a little bit more knowledge, I know what was wrong. It was definitely my fault. I've user a ROM that provided a patched version of TWRP that I was still using even tho I flashed another one.
